#lang racket

(sort
(apply
 append
(map
 (λ (tup) (list (list (third tup) (fifth tup))
                (list (fourth tup) (fifth tup))))
'(("MMFF" "Alice Berry /Wright/" "FFFFMFFF" "MFMFMMF" "Jane  /Tapp/")
 ("MMFF" "Alice Berry /Wright/" "FFFFMFFM" "MFMFMMM" "Robert  /Treat/")
 ("MMFF" "Alice Berry /Wright/" "FFFFMMFM" "MFMFMFM" "Richard  /Bryan/")
 ("MMFF" "Alice Berry /Wright/" "FFFMF" "MFMF" "Sarah  /Treat/")
 ("MMFF" "Alice Berry /Wright/" "FFFMM" "MFMM" "Benjamin  /Fenn/")
 ("MMFF" "Alice Berry /Wright/" "FFMFFMMF" "MMMMMFMF" "Mary  /Betts/")
 ("MMFF" "Alice Berry /Wright/" "FFMFFMMM" "MMMMMFMM" "Samuel  /Boreman/")
 ("MMFF" "Alice Berry /Wright/" "FFMMFFFFF" "MMMFMFFFF" "Unknown  /Unknown/")
 ("MMFF" "Alice Berry /Wright/" "FFMMFFFFM" "MMMFMFFFM" "Bigod  /Eggleston/")
 ("MMFF" "Alice Berry /Wright/" "FFMMMFFFFF" "MMMMMMFFF" "Elizabeth  /Deming/")
 ("MMFF" "Alice Berry /Wright/" "FFMMMFFFFM" "MMMMMMFFM" "Nathaniel  /Foote/")
 ("MMFF" "Alice Berry /Wright/" "FFMMMFMMFF" "MFMFMMMF" "Alice  /Gaylord/")
 ("MMFF" "Alice Berry /Wright/" "FFMMMFMMFM" "MFMFMMMM" "Richard  /Treat/")
 ("MMFF" "Alice Berry /Wright/" "FFMMMMFF" "MMMMMMFF" "Mary  /Foote/")
 ("MMFF" "Alice Berry /Wright/" "FFMMMMFM" "MMMMMMFM" "John  /Stoddard/")
 ("MMFF" "Alice Berry /Wright/" "FFMMMMM" "MMMMMMM" "Joseph  /Wright/"))))
string<?
#:key first)

'(;("FFFFMFFF" "Jane  /Tapp/")
  ;("FFFFMFFM" "Robert  /Treat/")
  ;("FFFFMMFM" "Richard  /Bryan/")
  ;("FFFMF" "Sarah  /Treat/")
  ;("FFFMM" "Benjamin  /Fenn/")
  ;("FFMFFMMF" "Mary  /Betts/")
  ;("FFMFFMMM" "Samuel  /Boreman/")
  ;("FFMMFFFFF" "Unknown  /Unknown/")
  ;("FFMMFFFFM" "Bigod  /Eggleston/")
  ("FFMMMFFFFF" "Elizabeth  /Deming/")
  ("FFMMMFFFFM" "Nathaniel  /Foote/")
  ("FFMMMFMMFF" "Alice  /Gaylord/")
  ("FFMMMFMMFM" "Richard  /Treat/")
  ("FFMMMMFF" "Mary  /Foote/")
  ("FFMMMMFM" "John  /Stoddard/")
  ("FFMMMMM" "Joseph  /Wright/")
  ;("MFMF" "Sarah  /Treat/")
  ;("MFMFMFM" "Richard  /Bryan/")
  ("MFMFMMF" "Jane  /Tapp/")
  ("MFMFMMM" "Robert  /Treat/")
  ("MFMFMMMF" "Alice  /Gaylord/")
  ("MFMFMMMM" "Richard  /Treat/")
  ;("MFMM" "Benjamin  /Fenn/")
  ("MMMFMFFFF" "Unknown  /Unknown/")
  ("MMMFMFFFM" "Bigod  /Eggleston/")
  ;("MMMMMFMF" "Mary  /Betts/")
  ;("MMMMMFMM" "Samuel  /Boreman/")
  ("MMMMMMFF" "Mary  /Foote/")
  ("MMMMMMFFF" "Elizabeth  /Deming/")
  ("MMMMMMFFM" "Nathaniel  /Foote/")
  ("MMMMMMFM" "John  /Stoddard/")
  ("MMMMMMM" "Joseph  /Wright/"))